### ISSUE TITLE
kaishiyoku/laravel-html-purifier does not support laravel version 7

### ISSUE THREAD

**Issue by justasLab** [Kaishiyoku/laravel-html-purifier#3]
I wanted to upgrade my project to Laravel7 today, but Composer returned an error:
# composer update 
Loading composer repositories with package information 
Updating dependencies (including require-dev) 
Your requirements could not be resolved to an installable set of packages. 

Problem 1 
- Conclusion: remove kaishiyoku/laravel-html-purifier 2.0.3 
- Conclusion: don’t install kaishiyoku/laravel-html-purifier 2.0.3 
  ...
- Conclusion: don’t install laravel/framework v7.0.0 
- kaishiyoku/laravel-html-purifier 2.0.0 requires illuminate/support 5.*

Is it possible to somehow upgrade my project to L7 without removing kaishiyoku purifier?

**Comment by Kaishiyoku** [comment]
@justasLab I read today that there is an ability in Composer to alias a version. However I could bump the laravel-html-purifier up to support Laravel 7 today when I'm at home in about 3 hours.

**Comment by Kaishiyoku** [comment]
@justasLab new version on Packagist, you can upgrade now
